In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
from sklearn.preprocessing import OneHotEncoder

#data encoding >> converting categorical column to numeric
#Nominal/OHE
#label and ordinal encoding
#target guided ordinal encoding



In [14]:
#single married, in a relationship
#single > [1, 0, 0]
#married > [0, 1, 0]
#separated > [0, 0, 1]
#nominal ohe >> binary vectors for each category

In [15]:
df = pd.DataFrame({'status': ['Single', 'Married', 'Single', 'Relationship', 'Married', 'Single']})

In [16]:
df

status
0        Single
1       Married
2        Single
3  Relationship
4       Married
5        Single

In [17]:
encoder=OneHotEncoder()#object of OneHotEncoder()
encoder

OneHotEncoder()

In [18]:
encoded = encoder.fit_transform(df[['status']]).toarray()

'''
fit will bring mue and sigma and transform will perform calculation
fit -> single,married,relationship
transform ->[1,0,0],[0,1,0],[0,0,1]
'''


'\nfit will bring mue and sigma and transform will perform calculation\nfit -> single,married,relationship\ntransform ->[1,0,0],[0,1,0],[0,0,1]\n'

In [19]:
encoded

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [23]:
encoder.get_feature_names_out()

array(['status_Married', 'status_Relationship', 'status_Single'],
      dtype=object)

In [31]:
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [27]:
#new data
encoder.transform([['Single']]).toarray()

array([[0., 0., 1.]])

In [32]:
final_df = pd.concat([df, encoder_df], axis = 1)

In [33]:
final_df

status  status_Married  status_Relationship  status_Single
0        Single             0.0                  0.0            1.0
1       Married             1.0                  0.0            0.0
2        Single             0.0                  0.0            1.0
3  Relationship             0.0                  1.0            0.0
4       Married             1.0                  0.0            0.0
5        Single             0.0                  0.0            1.0

In [35]:
final_df.drop(['status','status_Married'],inplace=True,axis=1)

In [36]:
final_df

status_Relationship  status_Single
0                  0.0            1.0
1                  0.0            0.0
2                  0.0            1.0
3                  1.0            0.0
4                  0.0            0.0
5                  0.0            1.0

In [37]:
df

status
0        Single
1       Married
2        Single
3  Relationship
4       Married
5        Single

In [39]:
pd.get_dummies(df['status'], drop_first=True,dtype=int)

Relationship  Single
0             0       1
1             0       0
2             0       1
3             1       0
4             0       0
5             0       1

Label Encoding

In [41]:
from sklearn.preprocessing import LabelEncoder

In [45]:
label_encoder = LabelEncoder()

In [46]:
label_encoder

LabelEncoder()

In [47]:
label_encoder.fit_transform(df[['status']])

array([2, 0, 2, 1, 0, 2])

In [48]:
df

status
0        Single
1       Married
2        Single
3  Relationship
4       Married
5        Single

Ordinal Encoding

In [49]:
from sklearn.preprocessing import OrdinalEncoder

In [50]:
df = pd.DataFrame({"qualification": ["HS", "PG","GR", "HS", "PhD", "HS", "PG"]})

In [51]:
df

qualification
0            HS
1            PG
2            GR
3            HS
4           PhD
5            HS
6            PG

In [54]:
encoder = OrdinalEncoder(categories = [["HS", "GR", "PG", "PhD"]])

In [55]:
encoder

OrdinalEncoder(categories=[['HS', 'GR', 'PG', 'PhD']])

In [56]:
encoder.fit_transform(df[['qualification']])

array([[0.],
       [2.],
       [1.],
       [0.],
       [3.],
       [0.],
       [2.]])

Target guided ordinal encoding

In [57]:
#target guided ordinal encoding
#relation with target variable
#A lot of unique categories
#replace with mean and and median

In [58]:
df = pd.DataFrame({'time': ['lunch', 'breakfast', 'dinner', 'lunch', 'breakfast', 'dinner', 'lunch', 'breakfast', 'dinner'],
             'total_bill': [120, 120, 40, 150, 160, 130,  40, 150, 160]})

In [59]:
df

time  total_bill
0      lunch         120
1  breakfast         120
2     dinner          40
3      lunch         150
4  breakfast         160
5     dinner         130
6      lunch          40
7  breakfast         150
8     dinner         160

In [60]:
mean_price = df.groupby('time')['total_bill'].mean().to_dict()

In [61]:
mean_price

{'breakfast': 143.33333333333334, 'dinner': 110.0, 'lunch': 103.33333333333333}

In [62]:
df['time_target_encoder']=df['time'].map(mean_price)

In [63]:
df

time  total_bill  time_target_encoder
0      lunch         120           103.333333
1  breakfast         120           143.333333
2     dinner          40           110.000000
3      lunch         150           103.333333
4  breakfast         160           143.333333
5     dinner         130           110.000000
6      lunch          40           103.333333
7  breakfast         150           143.333333
8     dinner         160           110.000000